### ISSUE TITLE
File.expand_path

### ISSUE THREAD

**Issue by duckinator** [bitboxer/manpages#10]
hi!

You should be able to replace the `File.join` on line 8 and `File.absolute_path(File.join(...))` on line 16 with `File.expand_path`

E.g., 

```ruby
  target_dir = File.expand_path(installer.bin_dir, "../share/man")
```

and

```ruby
  target_dir = File.expand_path(bin_dir, "../share/man")
```

**Comment by bitboxer** [comment]
Hi! 

Thanks for this. You are absolutely right. Fixed it now. If you see other parts that can be improved, just post them and I will fix them asap. This code was not reviewed by another person needs it.
