### ISSUE TITLE
Chore: In gemspec, replace git invocation with Dir[] + reject

### ISSUE THREAD

**Issue by olleolleolle** [bitboxer/manpages#41]
The gemspec makes the target system rely on Git being installed. No need, really.

I noted this while looking at the gemspec, which has _no runtime dependencies_.

**Comment by bitboxer** [comment]
Yes, this is the default line that is added when creating a new gem with `bundle gem [gemname]`. And I really love that it skips files that are not in the git index when creating the gem file. If you don't have a better solution that does the same and doesn't rely on git, I will keep it in the gemspec.
